### ISSUE TITLE
feature request: Remove unwanted channels

### ISSUE THREAD

**Issue by 0xtrr** [NostrChat/NostrChat#25]
Hi!

As a user, I'd want to be able to remove channels I don't want to participate in anymore. All channels could have the same "options" button that channels you own yourself has where there is an option to leave the channel.

**Comment by talhasch** [comment]
We'll definitely have this feature soon.

**Comment by 0xtrr** [comment]
> @0xtrr #42 merged to development and will be at production soon.

Awesome, thanks!
