### ISSUE TITLE
feature request: donation link to the nostr-chat profile?

### ISSUE THREAD

**Issue by raphaellouisandress** [NostrChat/NostrChat#36]
would it be possible to include a donation link to the nostr-chat profile? what do you think of this idea? does this idea make sense?

![image](https://github.com/NostrChat/NostrChat/assets/132034879/458a7eac-3495-4981-a7b8-081a0684221c)

**Comment by talhasch** [comment]
Is it a NIP standard or do you know any other nostr apps use that custom field? @raphaellouisandress

**Comment by raphaellouisandress** [comment]
Hi @talhasch.

> Is it a NIP standard or do you know any other nostr apps use that custom field?

NIP 39 - External Identities in Profiles.
