### ISSUE TITLE
I think should be necessary only Mouseover to open Emoji, Gif and profile image. For now I need to click to open it

### ISSUE THREAD

**Issue by bitcoinuser** [NostrChat/NostrChat#7]
Hi,

I think should be necessary only Mouseover to open Emoji, Gif and profile image. For now I need to click to open it

Thanks.

**Comment by talhasch** [comment]
@bitcoinuser let me see how to do it.

**Comment by talhasch** [comment]
I checked some other popular chat apps like discord, slack and some others and all of them requires one click to open emoji, gif like popovers. I think it is better to follow their best practice in terms of UX. Closing this one.
